# Análisis de Medallas Olímpicas

## Cargar los datos

In [2]:
import pandas as pd
df = pd.read_csv("data/medallas.csv")

## Exploración Inicial

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     str
dtypes: float64(3), int64(1), str(1)
memory usage: 3.8 KB

## Limpieza de Datos

In [4]:
# Verificamos cuantos datos nulos existen en el dataframe
df.isnull().sum()

# Rellenamos eso datos nulos con "0"
df.fillna(0, inplace=True)
df

     Oro  Plata  Bronce  Total          Pais
0    0.0    1.0     2.0      3     Argentina
1    0.0    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    0.0    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   0.0    1.0     0.0      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    0.0     2.0      5    Uzbekistan
92   1.0    3.0     0.0      4     Venezuela

[93 rows x 5 columns]

In [5]:
# Corrección de datos erroneos
df["Oro"] = df["Oro"].astype(int)
df["Plata"] = df["Plata"].astype(int)
df["Bronce"] = df["Bronce"].astype(int)
df

    Oro  Plata  Bronce  Total          Pais
0     0      1       2      3     Argentina
1     0      2       2      4       Armenia
2    17      7      22     46     Australia
3     1      1       5      7       Austria
4     0      3       4      7    Azerbaijan
..  ...    ...     ...    ...           ...
88    0      1       0      1  Turkmenistan
89    2      1       1      4        Uganda
90    1      6      12     19       Ukraine
91    3      0       2      5    Uzbekistan
92    1      3       0      4     Venezuela

[93 rows x 5 columns]

## Análisis de Medallas de Oro por País

In [6]:
df.sort_values(by=["Oro"], ascending=False).head(3)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
46   27     14      17     58                       Japon

## Análisis de Medallas Totales por País

In [7]:
dies_medallas = df[df["Total"] > 10]
dies_medallas.sort_values(by=["Total"], ascending=False)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
2    17      7      22     46                   Australia
32    1     11      16     37                     Germany
60    1     12      14     36                 Netherlands
30    1     12      11     33                      France
14    7      6      11     24                      Canada
11    7      6       8     21                      Brazil
90    1      6      12     19                     Ukraine
81    3      8       6     17                       Spain
19    7      3       5     15                        Cuba
66    4      5       5     14                      Poland
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
15    2      4       6     12              Chinese Taipei
20    4      4       3     11              Czech Republic
21    3      4       4     11                     Denmark